package main

import (
	"encoding/json"
	"log"
	"net/http"
	"os"
	"sync"
	"time"

	"github.com/gorilla/websocket"
)

// ============================================================
// CONFIGURATION
// ============================================================

const (
	serverDataFile = "server_data.json"

	retryInterval = 5 * time.Second

	// Maximum number of pending packets kept for one user.
	maxPendingPerUser = 100
)

// ============================================================
// CLIENT
// ============================================================

type Client struct {
	Username string
	Conn     *websocket.Conn

	// Protects concurrent writes to this WebSocket connection.
	WriteMutex sync.Mutex
}

// ============================================================
// PACKET
// ============================================================

type Packet struct {
	Type     string          `json:"type"`
	Username string          `json:"username,omitempty"`
	Sender   string          `json:"sender,omitempty"`
	Target   string          `json:"target,omitempty"`
	Payload  json.RawMessage `json:"payload,omitempty"`
}

// ============================================================
// PERSISTENT PENDING PACKET
// ============================================================

type PendingPacket struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	Packet    Packet    `json:"packet"`
}

// ============================================================
// BLACKLIST ENTRY
// ============================================================
//
// Every deleted account becomes one blacklist entry.
//
// Username identifies the account name.
// PublicID identifies the cryptographic identity.
//
// Later, this can be extended with signatures without changing
// the account deletion flow.
// ============================================================

type BlacklistEntry struct {
	Username string `json:"username"`
	PublicID string `json:"publicId"`
}

// ============================================================
// BLACKLIST
// ============================================================
//
// The server owns this blacklist.
//
// Version increases whenever a NEW account is added.
// Existing entries are not duplicated.
//
// Payload is generated by the server from Entries.
//
// Current format:
//
// {
//   "version": 1,
//   "updatedAt": "...",
//   "entries": [
//     {
//       "username": "alice",
//       "publicId": "..."
//     }
//   ]
// }
//
// Later we can add a cryptographic signature here.
// ============================================================

type BlacklistData struct {
	Version   int              `json:"version"`
	UpdatedAt time.Time        `json:"updatedAt"`
	Entries   []BlacklistEntry `json:"entries"`
}

// ============================================================
// SERVER PERSISTENT DATA
// ============================================================

type ServerData struct {
	PendingPackets []PendingPacket `json:"pendingPackets"`
	Blacklist      BlacklistData  `json:"blacklist"`
}

// ============================================================
// GLOBAL STATE
// ============================================================

var (
	clients = make(map[string]*Client)

	data = ServerData{
		PendingPackets: []PendingPacket{},
		Blacklist: BlacklistData{
			Version:   0,
			UpdatedAt: time.Time{},
			Entries:   []BlacklistEntry{},
		},
	}

	mutex sync.RWMutex

	upgrader = websocket.Upgrader{
		CheckOrigin: func(r *http.Request) bool {
			return true
		},
	}
)

// ============================================================
// PERSISTENT STORAGE
// ============================================================

func loadServerData() error {
	mutex.Lock()
	defer mutex.Unlock()

	file, err := os.Open(serverDataFile)

	if os.IsNotExist(err) {
		log.Println("[STORAGE] No existing server data found.")
		return nil
	}

	if err != nil {
		return err
	}

	defer file.Close()

	var loaded ServerData

	decoder := json.NewDecoder(file)

	if err := decoder.Decode(&loaded); err != nil {
		return err
	}

	if loaded.PendingPackets == nil {
		loaded.PendingPackets = []PendingPacket{}
	}

	if loaded.Blacklist.Entries == nil {
		loaded.Blacklist.Entries = []BlacklistEntry{}
	}

	data = loaded

	log.Println(
		"[STORAGE] Loaded",
		len(data.PendingPackets),
		"pending packets",
	)

	log.Println(
		"[STORAGE] Blacklist version:",
		data.Blacklist.Version,
	)

	log.Println(
		"[STORAGE] Blacklist entries:",
		len(data.Blacklist.Entries),
	)

	return nil
}

func saveServerDataLocked() error {
	tempFile := serverDataFile + ".tmp"

	file, err := os.Create(tempFile)
	if err != nil {
		return err
	}

	encoder := json.NewEncoder(file)
	encoder.SetIndent("", "  ")

	if err := encoder.Encode(data); err != nil {
		file.Close()
		return err
	}

	if err := file.Sync(); err != nil {
		file.Close()
		return err
	}

	if err := file.Close(); err != nil {
		return err
	}

	if err := os.Rename(tempFile, serverDataFile); err != nil {
		return err
	}

	return nil
}

// ============================================================
// SEND DIRECTLY TO CONNECTED USER
// ============================================================
//
// WebRTC signaling remains ephemeral.
//
// There is NO queue here.
//
// If the target is not connected, the packet is discarded.
//
// The WriteMutex only prevents multiple goroutines from writing
// to the same WebSocket connection simultaneously.
// ============================================================

func sendToUser(targetUsername string, packet Packet) bool {
	mutex.RLock()
	target, ok := clients[targetUsername]
	mutex.RUnlock()

	if !ok {
		return false
	}

	// Gorilla WebSocket supports one concurrent reader and one
	// concurrent writer, but multiple concurrent writers are not
	// safe.
	target.WriteMutex.Lock()
	defer target.WriteMutex.Unlock()

	if err := target.Conn.WriteJSON(packet); err != nil {
		log.Println(
			"[FORWARD ERROR]",
			targetUsername,
			err,
		)

		return false
	}

	return true
}

// ============================================================
// PENDING PACKET ID
// ============================================================

func makePacketID(packet Packet) string {
	return packet.Type + ":" +
		packet.Sender + ":" +
		packet.Target + ":" +
		time.Now().UTC().Format("20060102150405.000000000")
}

// ============================================================
// ADD PENDING PACKET
// ============================================================

func addPendingPacket(packet Packet) {
	mutex.Lock()
	defer mutex.Unlock()

	// Prevent duplicate queue entries for the exact same
	// packet type/sender/target/payload.
	packetJSON, _ := json.Marshal(packet)

	for _, pending := range data.PendingPackets {
		existingJSON, _ := json.Marshal(pending.Packet)

		if string(existingJSON) == string(packetJSON) {
			return
		}
	}

	// Protect the server from unlimited queued requests.
	count := 0

	for _, pending := range data.PendingPackets {
		if pending.Packet.Target == packet.Target {
			count++
		}
	}

	if count >= maxPendingPerUser {
		log.Println(
			"[QUEUE] target queue full:",
			packet.Target,
		)

		return
	}

	pending := PendingPacket{
		ID:        makePacketID(packet),
		CreatedAt: time.Now().UTC(),
		Packet:    packet,
	}

	data.PendingPackets = append(
		data.PendingPackets,
		pending,
	)

	if err := saveServerDataLocked(); err != nil {
		log.Println("[STORAGE ERROR]", err)
	}

	log.Println(
		"[QUEUE]",
		packet.Type,
		packet.Sender,
		"->",
		packet.Target,
	)
}

// ============================================================
// REMOVE PENDING PACKET
// ============================================================

func removePendingPacket(id string) {
	mutex.Lock()
	defer mutex.Unlock()

	filtered := make(
		[]PendingPacket,
		0,
		len(data.PendingPackets),
	)

	for _, pending := range data.PendingPackets {
		if pending.ID != id {
			filtered = append(filtered, pending)
		}
	}

	data.PendingPackets = filtered

	if err := saveServerDataLocked(); err != nil {
		log.Println("[STORAGE ERROR]", err)
	}
}

// ============================================================
// DELIVER PENDING PACKETS TO ONE USER
// ============================================================

func deliverPendingToUser(username string) {
	mutex.RLock()

	pending := make([]PendingPacket, 0)

	for _, item := range data.PendingPackets {
		if item.Packet.Target == username {
			pending = append(pending, item)
		}
	}

	mutex.RUnlock()

	if len(pending) == 0 {
		return
	}

	log.Println(
		"[QUEUE]",
		"delivering",
		len(pending),
		"pending packets to",
		username,
	)

	for _, item := range pending {

		if !sendToUser(username, item.Packet) {
			// Stop here if connection failed.
			// The packet remains pending.
			return
		}

		removePendingPacket(item.ID)

		log.Println(
			"[QUEUE DELIVERED]",
			item.Packet.Type,
			item.Packet.Sender,
			"->",
			username,
		)
	}
}

// ============================================================
// RETRY ALL PENDING PACKETS
// ============================================================

func retryPendingPackets() {
	mutex.RLock()

	pending := make([]PendingPacket, len(data.PendingPackets))
	copy(pending, data.PendingPackets)

	mutex.RUnlock()

	if len(pending) == 0 {
		return
	}

	log.Println(
		"[RETRY] checking",
		len(pending),
		"pending packets",
	)

	for _, item := range pending {

		mutex.RLock()
		_, connected := clients[item.Packet.Target]
		mutex.RUnlock()

		if !connected {
			continue
		}

		if !sendToUser(item.Packet.Target, item.Packet) {
			continue
		}

		removePendingPacket(item.ID)

		log.Println(
			"[RETRY DELIVERED]",
			item.Packet.Type,
			item.Packet.Sender,
			"->",
			item.Packet.Target,
		)
	}
}

// ============================================================
// RETRY LOOP
// ============================================================

func startRetryLoop() {
	ticker := time.NewTicker(retryInterval)

	go func() {
		for range ticker.C {
			retryPendingPackets()
		}
	}()
}

// ============================================================
// STORE OR FORWARD PACKET
// ============================================================
//
// Used ONLY for:
//
// - conversation_request
// - conversation_accept
// - conversation_reject
//
// WebRTC signaling does NOT use this function.
// ============================================================

func queueOrSend(packet Packet) {
	if packet.Target == "" {
		return
	}

	// Always persist first.
	addPendingPacket(packet)

	// Then immediately attempt delivery.
	if sendToUser(packet.Target, packet) {

		mutex.RLock()

		var deliveredID string

		packetJSON, _ := json.Marshal(packet)

		for _, pending := range data.PendingPackets {
			existingJSON, _ := json.Marshal(pending.Packet)

			if string(existingJSON) == string(packetJSON) {
				deliveredID = pending.ID
				break
			}
		}

		mutex.RUnlock()

		if deliveredID != "" {
			removePendingPacket(deliveredID)

			log.Println(
				"[DELIVERED]",
				packet.Type,
				packet.Sender,
				"->",
				packet.Target,
			)
		}

		return
	}

	log.Println(
		"[PENDING]",
		packet.Type,
		packet.Sender,
		"->",
		packet.Target,
	)
}

// ============================================================
// ADD ACCOUNT TO BLACKLIST
// ============================================================

func addDeletedAccountToBlacklist(
	username string,
	publicID string,
) bool {

	mutex.Lock()
	defer mutex.Unlock()

	// Prevent duplicate entries.
	for _, entry := range data.Blacklist.Entries {

		if entry.Username == username &&
			entry.PublicID == publicID {

			log.Println(
				"[BLACKLIST] account already exists:",
				username,
			)

			return false
		}
	}

	// Add the deleted account.
	data.Blacklist.Entries = append(
		data.Blacklist.Entries,
		BlacklistEntry{
			Username: username,
			PublicID: publicID,
		},
	)

	// Increase blacklist version.
	data.Blacklist.Version++

	data.Blacklist.UpdatedAt = time.Now().UTC()

	// Persist everything.
	if err := saveServerDataLocked(); err != nil {
		log.Println(
			"[BLACKLIST STORAGE ERROR]",
			err,
		)

		return false
	}

	log.Println(
		"[BLACKLIST] added deleted account:",
		username,
		"version:",
		data.Blacklist.Version,
	)

	return true
}

// ============================================================
// MAKE BLACKLIST PAYLOAD
// ============================================================

func makeBlacklistPayload() json.RawMessage {
	mutex.RLock()
	defer mutex.RUnlock()

	payload := struct {
		Version   int              `json:"version"`
		UpdatedAt time.Time        `json:"updatedAt"`
		Entries   []BlacklistEntry `json:"entries"`
	}{
		Version:   data.Blacklist.Version,
		UpdatedAt: data.Blacklist.UpdatedAt,
		Entries: append(
			[]BlacklistEntry(nil),
			data.Blacklist.Entries...,
		),
	}

	encoded, err := json.Marshal(payload)

	if err != nil {
		log.Println(
			"[BLACKLIST] failed to encode payload:",
			err,
		)

		return json.RawMessage(`{}`)
	}

	return json.RawMessage(encoded)
}

// ============================================================
// SEND BLACKLIST TO ONE USER
// ============================================================

func sendBlacklistToUser(username string) {

	mutex.RLock()

	version := data.Blacklist.Version

	mutex.RUnlock()

	// No deleted accounts yet.
	if version == 0 {
		return
	}

	packet := Packet{
		Type:   "blacklist_update",
		Target: username,
		Payload: makeBlacklistPayload(),
	}

	if sendToUser(username, packet) {

		log.Println(
			"[BLACKLIST] sent version",
			version,
			"to",
			username,
		)
	}
}

// ============================================================
// BROADCAST BLACKLIST
// ============================================================

func broadcastBlacklist() {

	mutex.RLock()

	connectedUsers := make(
		[]string,
		0,
		len(clients),
	)

	for username := range clients {
		connectedUsers = append(
			connectedUsers,
			username,
		)
	}

	version := data.Blacklist.Version

	mutex.RUnlock()

	log.Println(
		"[BLACKLIST] broadcasting version",
		version,
		"to",
		len(connectedUsers),
		"connected users",
	)

	for _, username := range connectedUsers {
		sendBlacklistToUser(username)
	}
}

// ============================================================
// WEBSOCKET CONNECTION
// ============================================================

func handleConnection(w http.ResponseWriter, r *http.Request) {

	conn, err := upgrader.Upgrade(w, r, nil)

	if err != nil {
		log.Println(
			"WebSocket upgrade failed:",
			err,
		)

		return
	}

	defer conn.Close()

	var username string

	for {

		var packet Packet

		if err := conn.ReadJSON(&packet); err != nil {
			break
		}

		switch packet.Type {

		// ====================================================
		// REGISTER
		// ====================================================

		case "register":

			if packet.Username == "" {
				continue
			}

			username = packet.Username

			mutex.Lock()

			if oldClient, exists := clients[username]; exists {

				_ = oldClient.Conn.Close()

				log.Println(
					"[REGISTER] replaced old connection:",
					username,
				)
			}

			clients[username] = &Client{
				Username: username,
				Conn:     conn,
			}

			mutex.Unlock()

			log.Println(
				"[REGISTER]",
				username,
				"connected",
			)

			// Deliver pending conversation packets.
			deliverPendingToUser(username)

			// Send latest blacklist.
			sendBlacklistToUser(username)

		// ====================================================
		// CONVERSATION REQUEST
		// ====================================================

		case "conversation_request":

			if packet.Target == "" ||
				packet.Sender == "" {

				continue
			}

			log.Println(
				"[CONVERSATION REQUEST]",
				packet.Sender,
				"->",
				packet.Target,
			)

			queueOrSend(packet)

		// ====================================================
		// CONVERSATION ACCEPT
		// ====================================================

		case "conversation_accept":

			if packet.Target == "" ||
				packet.Sender == "" {

				continue
			}

			log.Println(
				"[CONVERSATION ACCEPT]",
				packet.Sender,
				"->",
				packet.Target,
			)

			queueOrSend(packet)

		// ====================================================
		// CONVERSATION REJECT
		// ====================================================

		case "conversation_reject":

			if packet.Target == "" ||
				packet.Sender == "" {

				continue
			}

			log.Println(
				"[CONVERSATION REJECT]",
				packet.Sender,
				"->",
				packet.Target,
			)

			queueOrSend(packet)

		// ====================================================
		// WEBRTC SIGNALING
		// ====================================================

		case "offer",
			"answer",
			"candidate",
			"signal":

			if packet.Target == "" {
				continue
			}

			log.Println(
				"[SIGNAL]",
				packet.Type,
				"from",
				packet.Sender,
				"to",
				packet.Target,
			)

			// WebRTC signaling is intentionally ephemeral.
			//
			// If the target is not connected right now,
			// the packet is discarded.
			//
			// No TURN.
			// No relay.
			// No persistent WebRTC signaling queue.
			sendToUser(packet.Target, packet)

		// ====================================================
		// BLACKLIST REQUEST
		// ====================================================

		case "blacklist_request":

			if packet.Sender == "" {
				continue
			}

			log.Println(
				"[BLACKLIST REQUEST]",
				packet.Sender,
			)

			sendBlacklistToUser(packet.Sender)

		// ====================================================
		// ACCOUNT DELETED
		// ====================================================

		case "account_deleted":

			if packet.Sender == "" {
				log.Println(
					"[ACCOUNT DELETED] missing sender",
				)

				continue
			}

			if len(packet.Payload) == 0 {
				log.Println(
					"[ACCOUNT DELETED] missing payload",
				)

				continue
			}

			var deletion struct {
				Username string `json:"username"`
				PublicID string `json:"publicId"`
			}

			if err := json.Unmarshal(
				packet.Payload,
				&deletion,
			); err != nil {

				log.Println(
					"[ACCOUNT DELETED] invalid payload:",
					err,
				)

				continue
			}

			if deletion.Username == "" ||
				deletion.PublicID == "" {

				log.Println(
					"[ACCOUNT DELETED] missing username or publicId",
				)

				continue
			}

			// The sender must match the account being deleted.
			if packet.Sender != deletion.Username {
				log.Println(
					"[ACCOUNT DELETED] sender mismatch:",
					packet.Sender,
					"!=",
					deletion.Username,
				)

				continue
			}

			log.Println(
				"[ACCOUNT DELETED]",
				deletion.Username,
				deletion.PublicID,
			)

			added := addDeletedAccountToBlacklist(
				deletion.Username,
				deletion.PublicID,
			)

			// Only broadcast if the blacklist actually changed.
			if added {
				broadcastBlacklist()
			}

		// ====================================================
		// UNKNOWN PACKET
		// ====================================================

		default:

			log.Println(
				"[UNKNOWN PACKET]",
				packet.Type,
				"from",
				packet.Sender,
			)
		}
	}

	// ========================================================
	// CLEANUP
	// ========================================================

	if username != "" {

		mutex.Lock()

		if client, exists := clients[username]; exists &&
			client.Conn == conn {

			delete(clients, username)
		}

		mutex.Unlock()

		log.Println(
			username,
			"disconnected",
		)
	}
}

// ============================================================
// MAIN
// ============================================================

func main() {

	if err := loadServerData(); err != nil {
		log.Fatal(
			"[STORAGE] Failed to load server data:",
			err,
		)
	}

	startRetryLoop()

	http.HandleFunc(
		"/ws",
		handleConnection,
	)

	port := os.Getenv("PORT")

	if port == "" {
		port = "8080"
	}

	log.Println(
		"CRYPT signaling server running on :"+port,
	)

	log.Println(
		"[STORAGE] Persistent data:",
		serverDataFile,
	)

	log.Println(
		"[QUEUE] Retry interval:",
		retryInterval,
	)

	err := http.ListenAndServe(
		"0.0.0.0:"+port,
		nil,
	)

	if err != nil {
		log.Fatal(err)
	}
}